name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community
      - name: Copy data folder from geo to domain-list-community
        run: |
          rm -rf "domain-list-community/data"
          cp -R "$GITHUB_WORKSPACE/data" "domain-list-community/mydata"
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Build geosite.dat file
        run: |
          go run ./ --datapath=domain-list-community/mydata
          cp -f dlc.dat "$GITHUB_WORKSPACE/my-geosite.dat"
        working-directory: domain-list-community
      - name: Upload geosite.dat to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto-${{ github.run_number }}
          name: Auto Release ${{ github.run_number }}
          body: Automated release from push to main.
          files: geosite.dat
